### ISSUE TITLE
Add options to not use bias in Linear (and Conv in future)

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#100]
I think this code be done by implementing `Linear` as a tuple instead: `(MatMul<I, O>, Add<O>)`, and then if someone doesn't want bias, they can just `MatMul<I, O>` instead.

However, this would break linear's `.npz` compatibility with pytorch.

**Comment by coreylowman** [comment]
Maybe a better option is to include bias as a `const BIAS: bool = true` generic param.

**Comment by jafioti** [comment]
I think having a Linear module is much better than just using a tuple. I feel like if you specifically want no bias, then just use `MatMul<I, O>`

**Comment by M1ngXU** [comment]
> I think having a Linear module is much better than just using a tuple. I feel like if you specifically want no bias, then just use `MatMul<I, O>`

i think it's something like this
`type Linear<I, O> = (MatMul<I, O>, Add<O>)`

(and maybe `type LinearNoBias<I, O> = MatMul<I, O>`)
