### ISSUE TITLE
Make docstrings consistent with comparisons to other framework apis

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#115]
There are a number of tensor_ops that try to detail the equivalent operation in pytorch in their docstring. Make all of these docstrings a consistent format to reduce confusion.

_Originally posted by @M1ngXU in https://github.com/coreylowman/dfdx/issues/109#issuecomment-1191629280_

**Comment by jafioti** [comment]
I think this is a good idea, but I do thing the operations are moving pretty fast (like the potential cutting down on matmul functions) so I'm not sure if its a good idea to invest time in docs for functions that may change soon. Maybe when operations are a little more stable (hopefully real soon) it makes more sense.
