### ISSUE TITLE
0.9.0 release

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#127]
Tracking issue for next release

- [x] #34 
- [x] #55 
- [x] #1 
- [x] #67 
- [x] #123 
- [x] #115
- [x] #111
- [x] #96 
- [ ] #122
- [x] #114 
- [x] #139 
- [x] #137

**Comment by M1ngXU** [comment]
> * Tensor with 2-max-values in Max Last stores wrong gradients #111

according to your last comment in that issue, we just have to change the docstring?

**Comment by coreylowman** [comment]
> > * Tensor with 2-max-values in Max Last stores wrong gradients [Tensor with 2-max-values in Max Last stores wrong gradients #111](https://github.com/coreylowman/dfdx/issues/111)
> 
> according to your last comment in that issue, we just have to change the docstring?

yep!
