### ISSUE TITLE
Cargo test fails with weird linker errors on main branch

### ISSUE THREAD

**Issue by vikigenius** [coreylowman/dfdx#154]
Just noticed that running `cargo test` on the main branch produces a huge bunch of weird linker errors

```rust
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

warning: `dfdx` (example "conv_net") generated 1 warning
error: could not compile `dfdx` due to previous error; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit status: 1
```

This is not the full error trace. The full one is huge, just wanted to confirm if this is an issue.

**Comment by coreylowman** [comment]
What version of nightly are you using?

**Comment by vikigenius** [comment]
Yeah you were right, updating the nightly toolchain did fix the issue. Previously the nightly version was 1.64 which was causing the error. But it went away after updating to 1.65 today.

**Comment by coreylowman** [comment]
Okay cool, yeah linker issues went away for me after updating a week or two ago. I hope it doesn't regress!
