### ISSUE TITLE
QUESTION: Possibility of using the lib to compile with no_std for embedding

### ISSUE THREAD

**Issue by antimora** [coreylowman/dfdx#196]
I recently discovered your library, and I think it's great. I have a requirement to compile NN with `no_std` for inferencing in an embedded setting. I am wondering if this is possible with `dfdx` or how easy it would be to modify

**Comment by coreylowman** [comment]
Thanks for reaching out! This is an interesting one. I haven't worked with `no_std` before, but looking at https://docs.rust-embedded.org/book/intro/no-std.html#overview, it seems like at minimum we'd have to swap to using the `alloc` crate for allocations & `Rc`. Also all the `nn` serialization code uses `std::io`, which I'm not seeing in core?

Also depend on `rand`, `rand_distr`, and `matrixmultiply` which all do support `no_std`.

Overall this seems plausible and definitely a good use case for dfdx to support.

**Comment by antimora** [comment]
Thank you for answering and creating a task to support this feature. It would be greatly appreciated by me and the greater Rust community. Your library would be an excellent addition to this growing list of libs: https://lib.rs/no-std. 

We close this ticket as answered.
