### ISSUE TITLE
`no_std` support

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#201]
First asked in #196 

- [x] use `allocations` for `Rc` and allocating
- [x] use `collections` for hashmap and vec
- [x] add `std` feature
- [x] only depend on zip when std is enabled
- [x] only include serialization & numpy with `std` feature

**Comment by antimora** [comment]
This crate (https://lib.rs/crates/no-std-compat) might be helpful for migration. I haven't used it but stumbled recently.

**Comment by coreylowman** [comment]
Re-opening, seems like I misunderstood how turning off default features worked
