### ISSUE TITLE
Question: how to make a recurrent network?

### ISSUE THREAD

**Issue by Dimev** [coreylowman/dfdx#202]
How can I make a recurrent network?

Is it just running the different inputs through the netwrok several times, while reusing the hidden state produced by it?

**Comment by coreylowman** [comment]
Pretty much yeah - except the hidden state is updated after each forward pass. Usually they take a tuple as input `(input, hidden_state)`, and return a tuple as output `(output, new hidden state)`. This is how they would work in dfdx as well.

Currently there are no RNN/LSTM layers in `dfdx`, but would happily accept a contribution from people!
