### ISSUE TITLE
Support for conv1d

### ISSUE THREAD

**Issue by antimora** [coreylowman/dfdx#219]
Currently `dfdx` supports `conv2d`, it would be if `conv1d` is supported out of the box. I know it'd be possible to use conv2d as a workaround but the code would not look clean.

**Comment by coreylowman** [comment]
Yeah definitely want to support in the future. Happy to help/accept a contribution of this (would need to add to devices/conv.rs, tensor_ops/conv.rs and nn/conv.rs). Otherwise my focus is on the next release & GPU support currently.

**Comment by mert-kurttutan** [comment]
Continuing the issue here:
Before dividing into codebase, are you still open to contribution for conv1d implementation?

**Comment by coreylowman** [comment]
Of course! Happy to review or help as necessary, convolutions are definitely the most complicated operator we have

**Comment by jcrist1** [comment]
I ported of the GPT2Transformer from hugging face to dfdx and implemented a conv1d there. Would be happy to see if it can be brought in here. @mert-kurttutan how far along are you?

**Comment by jcrist1** [comment]
Well I decided to implement this [here](https://github.com/coreylowman/dfdx/pull/807/files), but while implementing realised that it's not at all the Conv1D I use or needed from [transformers](https://github.com/huggingface/transformers/blob/35eac0df75c692c5b93c12f7eaf3279cab8bd7ce/src/transformers/pytorch_utils.py#L85) but I put in the work, so may as well at lease see if it does the job 😄

**Comment by optman** [comment]
no bias support.
