### ISSUE TITLE
Can't use transformers?

### ISSUE THREAD

**Issue by davidatsurge** [coreylowman/dfdx#245]
Here's an excerpt from the transformer tests in the repo, except in a binary that has `dfdx` as a dependency. It fails to compile because of trait bound errors:

```rust
use dfdx::{
    nn::{ResetParams, Transformer},
    prelude::*,
};
use rand::{prelude::StdRng, SeedableRng};

fn main() { // the stuff in main() is from dfdx's nn/transformers/mod.rs tests.
    let mut rng = StdRng::seed_from_u64(0);
    let mut t: Transformer<16, 4, 3, 3, 8> = Default::default();
    t.reset_params(&mut rng);

    let src: Tensor3D<4, 12, 16> = TensorCreator::randn(&mut rng);
    let tgt: Tensor3D<4, 6, 16> = TensorCreator::randn(&mut rng);
    let out: Tensor3D<4, 6, 16, _> = t.forward_mut((src.trace(), tgt)); // complains about trait bounds
    let g = backward(out.mean());
}
```

Help?

This is all on current HEAD (163b984), btw.

**Comment by davidatsurge** [comment]
While trying to figure this out, I realized the following patch breaks the transformer tests in `nn/transformers/mod.rs` with a very similar trait bounds error.

```diff
diff --git a/src/nn/transformer/mod.rs b/src/nn/transformer/mod.rs
index 4413009..5bcb467 100644
--- a/src/nn/transformer/mod.rs
+++ b/src/nn/transformer/mod.rs
@@ -4,7 +4,6 @@ mod mha;
 
 pub use decoder::*;
 pub use encoder::*;
-pub use mha::*;
 
 use crate::gradients::{CanUpdateWithGradients, GradientProvider, UnusedTensors};
 use crate::prelude::*;
```

But I can't figure out _what_ from `mha.rs` is required, because as far as I can see, nothing from `mha.rs` (a struct or a trait) is used in `nn/transformer/mod.rs`.

**Comment by coreylowman** [comment]
Thanks for raising, this is maybe more subtle than I realized, but as of https://github.com/coreylowman/dfdx/pull/242, the actual module impl's require you to be on nightly and have generic_const_exprs enabled.

Can you try adding `#![feature(generic_const_exprs)]` and running with `cargo +nightly run ...`?

Might revert that change to make it so you have to enable nightly to even get access. This will be the same issue with a number of modules

**Comment by coreylowman** [comment]
Specifically, mha `impl Module` have a nightly requirement around them: https://github.com/coreylowman/dfdx/blob/main/src/nn/transformer/mha.rs#L57.

**Comment by davidatsurge** [comment]
Adding `#![feature(generic_const_exprs)]` does work with the latest master. Thanks @coreylowman! Looking forward to taking this for a test drive :D
