### ISSUE TITLE
Cpu::zeros::<T> is unsound for some T

### ISSUE THREAD

**Issue by gmorenz** [coreylowman/dfdx#252]
There's a [comment in the implementation](https://github.com/coreylowman/dfdx/blob/main/src/devices/allocate.rs#L14) asking "TODO is this function safe for any T?". It isn't, various types are defined to not take on various values (rust calls these niches), and forcing them to do so is undefined behavior.

Examples include `std::num::NonZeroU32` and friends, references, any enum with no variant that is tagged as 0, etc.

Below is an example where miri will catch undefined behavior and complain ("encounted 0, but expected something greater or equal to 1").

```rust
use dfdx::{
    arrays::CountElements,
    devices::AllocateZeros,
};

#[repr(transparent)]
#[derive(Clone, Copy)]
struct Illegal {
    inner: std::num::NonZeroU32
}

impl CountElements for Illegal {
    type Dtype = Self;
    const NUM_ELEMENTS: usize = 1;
    const NUM_BYTES: usize = 4;

    fn ref_first_elem(&self) -> &Self::Dtype {
        todo!()
    }

    fn mut_first_elem(&mut self) -> &mut Self::Dtype {
        todo!()
    }
}

fn main() {
    dfdx::devices::Cpu::zeros::<Illegal>().inner;
}
```

**Comment by coreylowman** [comment]
Perhaps adding an `unsafe trait ValidAsAllZeroBits` marker trait would address this? At least then its explicit

**Comment by gmorenz** [comment]
That seems like a good solution to me :+1:

**Comment by gmorenz** [comment]
Maybe this should actually just piggyback on `ZeroElements` (making that trait unsafe)?

It ends up infecting a lot of APIs, and whenever placement new finally becomes a thing it would probably make sense to just write it as (`box T::zeros`) - at least on the CPU device.
