### ISSUE TITLE
Add Cpu device with StridedArrays as storage

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#270]
Related to #265, #9 , #186 

This is dependent on GATs and the device refactor. Basically this would implement device like:

```rust
trait Device {
    type Storage<T: CountElements>;
}

struct CpuStrided;

impl Device for CpuStrided {
    type Storage<T> = StridedArray<T>;
}

struct StridedArray<T: CountElements> {
    data: Vec<T::Dtype>,
    strides: Vec<usize>,
    marker: PhantomData<*const T>,
}
```

Where strided array stores data in a flat vector, and also keeps track of strides. This would enable zero copy broadcasts/permutes by changing the strides.

**Comment by coreylowman** [comment]
FYA @jafioti and @vikigenius, I finally figured out a good path forward for strided arrays (first mentioned in #108) that will use GATs. Basically the same approach to having a cuda device will also work for CPU device with different methods of storing data. Under the hood the `StridedArray` will just be a Vec of data, but will carry along a generic parameter that is the array that it represents (see above). This will ensure typing information is carried along everywhere (and is known at compile time).

I've been testing this all locally in a separate repo, but will be a bit before I merge it into dfdx.

After this a number of simplifications will emerge:
1. the `Cpu` device will probably point to the new strided one
2. The un-strided cpu device will *always* do copies for broadcasting/permutes/etc. It will likely be featured gated as a test/debugging device.
3. Can remove the various matmul transpose ops & the various device level mm_at/mm_atct/mm_bt. This only existed to get around the expensive copying of data that the un-strided version does. But now the strided arrays will handle this for us (and the un strided will just do the expensive copying).

**Comment by vikigenius** [comment]
I am not too familiar with GATs yet, it just got merged to stable after all. And will take a look.

But taking your it does sound valuable to do this. And it should be very convenient from both a user and maintenance perspective.

Looking forward to this.

**Comment by jafioti** [comment]
@coreylowman This is awesome! Would the un-strided versions even need to be kept after this? Seems like we can go fully strided which would eliminate a lot of the complexity / redundency.

Also this is a big step toward being able to use gpu kernels, as most of the ones today are built to work with strided arrays.

**Comment by jafioti** [comment]
@coreylowman Actually I'm a little confused by this, is this for a side thing just for CPU arrays, or is this going to be the core tensor data storage? I thought device was just a generic on the tensor.

Sorry, I haven't looked at the more recent changes you made.

**Comment by coreylowman** [comment]
@jafioti yeah device is generic on the tensor, but with how i'm planning devices out, they will have a GAT for how data is stored.

So the cuda device would be like:
```rust

struct Cuda { ... }

struct CudaTensor<T> { ... }

impl Device for Cuda {
    type Storage = CudaTensor<T>;
}
```

and then tensor structs would look like:
```rust
struct Tensor1D<const M: usize, Device> {
    data: Arc<Device::Storage<[f32; M]>>,
    ...
}
```

for the actual device traits/methods, they will all accept `&Self::Storage<T>`  in place of current `&T`.

**Comment by M1ngXU** [comment]
> Related to #265, #9 , #186
> 
> This is dependent on GATs and the device refactor. Basically this would implement device like:
> 
> ```rust
> trait Device {
>     type Storage<T: CountElements>;
> }
> 
> struct CpuStrided;
> 
> impl Device for CpuStrided {
>     type Storage<T> = StridedArray<T>;
> }
> 
> struct StridedArray<T: CountElements> {
>     data: Vec<T::Dtype>,
>     strides: Vec<usize>,
>     marker: PhantomData<*const T>,
> }
> ```
> 
> Where strided array stores data in a flat vector, and also keeps track of strides. This would enable zero copy broadcasts/permutes by changing the strides.

didn't read all the discussion, but wouldn't something like this make sense?
```rust
struct Tensor<const DimensionCount: usize, const ItemCount: usize, Device> {
    data: Arc<Device::Storage<[f32; ItemCount]>>,
    dimension_size: [usize; DimensionCount],
    dimension_stride: [usize; DimensionCount]
}
```
