### ISSUE TITLE
Could clones be prevented and performance increased ?

### ISSUE THREAD

**Issue by Valchap** [coreylowman/dfdx#300]
```rust
let mut m: Linear<4, 2> = Default::default();

let x: Tensor1D<4> = TensorCreator::zeros();
let _: Tensor1D<2> = m.forward(x); // Should use x.clone() for next forward to work

let _: Tensor1D<2> = m.forward(x); // Doesn't work, x has been moved by the last forward call
```

In this example it feels like x could be taken by reference &x to prevent useless copies and make it easier to use an input multiple times. Would it be a good idea to modify this or is there a good reason for using clones everywhere ?

**Comment by JYudelson1** [comment]
The data for a Tensor is stored in an [Arc](https://doc.rust-lang.org/nightly/alloc/sync/struct.Arc.html), so I think calling `.clone()` on a Tensor just makes another pointer & increments reference count, the actual data doesn't get cloned.

**Comment by Valchap** [comment]
Thanks, I think I get it. And it's probably not possible to get rid or arc clone because it may be problematic in multi threaded scenarios.
