### ISSUE TITLE
Add tensor_ops::where to replace value_mask

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#305]
Should roughly look like:

```rust
fn where<S: Shape, E: Dtype, D: Device<E>>(x: Tensor<S, E, D>, condition: Tensor<S, bool, D> , y: Tensor<S, E, D>) -> Tensor<S, E, D>;
```

Whichever is the self tensor for method version should be the one with the tape of the output.

ux:
```rust
let gt0 = x.clone().gt(0);
x.where(gt0, y);
```

**Comment by nkoppel** [comment]
Since 'where' is a keyword, I think I'm going to rename this operation to choose.
