### ISSUE TITLE
Optimize cuda sum_to kernel for full reductions

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#332]
Currently the sum_to reduction (& in the future max/min/etc) use atomicAdd to handle concurrent writes to the same output variable.

For reductions that reduce to 1 number this will result in a lot of contention for writes.

There should be a special kernel for reductions to 1 value based on standard reduction kernels. The sum_to kernel implementation can check at runtime if the size of the shape is 1 and execute the different kernel

_Originally posted by @coreylowman in https://github.com/coreylowman/dfdx/pull/331#discussion_r1063738025_

**Comment by M1ngXU** [comment]
reducing exists in cudnn

**Comment by coreylowman** [comment]
Agree using reduction from cudnn is ideal here, that will be the best we can do

**Comment by ViliamVadocz** [comment]
[CUB](https://nvlabs.github.io/cub/classcub_1_1_block_reduce.html) also exists as an option.
