### ISSUE TITLE
Matmul/Conv2d/Pool2d cuda kernels

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#333]
These will be more challenging to implement, since they will rely on a lot of code and invoking cublas.

Also need to see if there's a way to simplify the implementation (potentially by having a device level matmul trait that matmul/conv2d can use)

**Comment by coreylowman** [comment]
matmul tests blocked by #335

**Comment by coreylowman** [comment]
This will require sub views of CudaSlices, which will be addressed in cudarc

**Comment by M1ngXU** [comment]
all of them except matmul exist in cudnn
