### ISSUE TITLE
Implement cuda kernels for binary ops

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#334]
These can copy the setup for div cuda kernel, which is already implemented.

- [x] add
- [x] bce
- [x] div
- [x] huber_error
- [x] maximum
- [x] minimum
- [x] mul
- [x] sub

**Comment by M1ngXU** [comment]
add, min, max, mul exist in cudnn

**Comment by coreylowman** [comment]
Thanks @nkoppel
