### ISSUE TITLE
Implement select_to/gather_to cuda kernels

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#338]
These will be slightly more involved. Probably will be the most annoying cuda kernels to write.

**Comment by M1ngXU** [comment]
what exactly are these functions? in general, i am interested in writing cuda kernels ^^

**Comment by nkoppel** [comment]
@M1ngXU These functions are documented in https://github.com/coreylowman/dfdx/blob/main/src/tensor_ops/select_and_gather/mod.rs

**Comment by coreylowman** [comment]
Yeah they are for indexing (select selects an index from a dimension, gather gathers multiple indices from a dimension).

The CPU kernels are not as straightforward as some of the other ones (and there's a lot of duplicate code that could also be cleaned up), so this is probably the most complex after the matmul/pool/conv2d stuff
