### ISSUE TITLE
Add tensor_ops::prelu and nn::PReLU

### ISSUE THREAD

**Issue by leofidus** [coreylowman/dfdx#389]
Lately I've tried porting various computer vision networks to dfdx, and one function that seems quite popular in that field but isn't supported yet is PReLU. For now I just stay away from networks that use it, but it would be nice to have it available in the future.

https://pytorch.org/docs/stable/generated/torch.nn.PReLU.html#torch.nn.PReLU

ParametricReLU is bascially a LeakyReLU where the negative slope is a learned parameter, so there is going to be some overlap with the LeakyReLU implemenation (#287).

**Comment by TimerErTim** [comment]
Can this really be implemented on a tensor level? LeakyReLU should be no problem but PReLU, which effectively has learnable parameters, is not really possible on purely tensors, is it? nn::PReLU should be easy to do on the other hand.

**Comment by opfromthestart** [comment]
This should be closed
