### ISSUE TITLE
Slow compilation of VGG-16

### ISSUE THREAD

**Issue by leofidus** [coreylowman/dfdx#390]
Using the current dfdx master on the current nightly compiler, the code below takes 15 minutes to compile in release mode (after compiling all dependencies). Commenting out either the block labeled `conv block 5` or `head` drops the compile time to one minute.

```rust
#![feature(generic_const_exprs)]
use dfdx::{prelude::*, tensor::Tensor};

/// VGG-16
type Mlp = (
    // conv block 1
    (
        (Conv2D<3, 64, 3, 1, 1>, ReLU),
        (Conv2D<64, 64, 3, 1, 1>, ReLU),
        MaxPool2D<2, 2>,
    ),
    // conv block 2
    (
        (Conv2D<64, 128, 3, 1, 1>, ReLU),
        (Conv2D<128, 128, 3, 1, 1>, ReLU),
        MaxPool2D<2, 2>,
    ),
    // conv block 3
    (
        (Conv2D<128, 256, 3, 1, 1>, ReLU),
        (Conv2D<256, 256, 3, 1, 1>, ReLU),
        (Conv2D<256, 256, 3, 1, 1>, ReLU),
        MaxPool2D<2, 2>,
    ),
    // conv block 4
    (
        (Conv2D<256, 512, 3, 1, 1>, ReLU),
        (Conv2D<512, 512, 3, 1, 1>, ReLU),
        (Conv2D<512, 512, 3, 1, 1>, ReLU),
        MaxPool2D<2, 2>,
    ),
    // conv block 5
    (
        (Conv2D<512, 512, 3, 1, 1>, ReLU),
        (Conv2D<512, 512, 3, 1, 1>, ReLU),
        (Conv2D<512, 512, 3, 1, 1>, ReLU),
        MaxPool2D<2, 2>,
    ),
    // head
    (
        (Conv2D<512, 4096, 7, 1, 0>, ReLU),
        (Conv2D<4096, 4096, 1, 1, 0>, ReLU),
        (Conv2D<4096, 2622, 1, 1, 0>, Flatten2D, Softmax),
    ),
);

fn main() {
    let dev: Cpu = Default::default();
    let mlp: Mlp = dev.build_module();
    let x: Tensor<Rank3<3, 224, 224>> = dev.zeros();
    let y = Module::forward(&mlp, x);
}
```

I tried deeper tuples (grouping block 1-3 and 4-head), but that didn't seem to have an appreciable effect.

**Comment by coreylowman** [comment]
Oof yeah thanks for opening. Had a similar issue with resnet18 (#234). This is caused by the type inferencing that needs to occur because of:
1. Module implementations of tuple
2. Const generic transformations

There was a straightforward fix for the resnet at least, but I'll look into this. It seems like commenting out the MaxPool2D decreases the time significantly, so there could be an issue there.

I suspect Flatten2D might be causing some issue with type inference too

**Comment by coreylowman** [comment]
When I investigated this before, using a `Module<Input, Output>` formulation instead of associated type for Module::Output actually resolved the issue. But it's not possible to implement Module for tuples with the generic version

**Comment by coreylowman** [comment]
Linking seemingly related rustc issue https://github.com/rust-lang/rust/issues/106498

**Comment by coreylowman** [comment]
@leofidus With the linked PR I was able to get your example to only take a couple of seconds to compile. I've closed for now, but please try it out and verify on your end.

Also, the code you linked would be a great example along side the `examples/nightly-resnet18.rs`. Please contribute it!
