### ISSUE TITLE
Create tensors directly from vec's easily

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#399]
Right now you have to create the tensor first, then copy into the tensor from a vec. It'd be nice to just create a tensor directly from a vec. The underlying devices make this easy with `take_async` for cuda and you can already create a StridedArray with a vec with Cpu.

The main challenge will be figuring out a nice interface for both const/dyn shapes. I.e. for dyn shapes, the user needs to be able to specify the shape of the tensor, but that is not needed for const.

Also, this function/method should return a `Result<Tensor<...>, Vec<E>>`, in the case that the number of elements in the vec were not enough.

**Comment by nkoppel** [comment]
Here's what I've been drafting for this:
```rust
pub trait TensorFrom<S: Shape, Src, E: Unit>: DeviceStorage {
    fn tensor_with_shape(&self, src: Src, shape: &S) -> Tensor<S, E, Self> {
        self.try_tensor_with_shape(src, shape).unwrap()
    }

    fn try_tensor_with_shape(&self, src: Src, shape: &S) -> Result<Tensor<S, E, Self>, Self::Err>;
}

pub trait ConstShapeTensorFrom<S: ConstShape, Src, E: Unit>: DeviceStorage {
    fn tensor(&self, src: Src) -> Tensor<S, E, Self> {
        self.try_tensor(src).unwrap()
    }

    fn try_tensor(&self, src: Src) -> Result<Tensor<S, E, Self>, Self::Err>;
}

impl<S: ConstShape, Src, E: Unit, T: TensorFrom<S, Src, E>> ConstShapeTensorFrom<S, Src, E> for T {
    fn try_tensor(&self, src: Src) -> Result<Tensor<S, E, Self>, Self::Err> {
        self.try_tensor_with_shape(src, &S::default())
    }
}
```
This generalizes TensorFromArray, allowing `device.tensor()` to be polymorphic over arrays, vecs, iterators, etc.

**Comment by coreylowman** [comment]
Closed from PR above
