### ISSUE TITLE
[Ideation - Don't work on] Add DefaultDevice depending on feature flags - use in Tensor & all nn modules

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#410]
This has the potential to address #408 #388.

Potential to revert both #394, #405.

In many applications I'd expect we'd see something like this (and you can already see this in examples/06-mnist.rs:
```rust
#[cfg(not(feature = "cuda"))]
type Dev = Cpu;

#[cfg(feature = "cuda")]
type Dev = Cuda;
```

The idea of this issue is to add this to dfdx and then change both tensor & nn structs to use this:

```rust
struct Tensor<..., D: DeviceStorage = DefaultDevice> { ... }

struct Linear<..., D: DeviceStorage = DefaultDevice> { ... }
// etc
```

We can even go one step further and add another feature flag to override the default device, to make it settable by user.

# What this solves

- This makes it so you don't have to change any code to start using cuda, only turn on the feature flag
- This makes it so you shouldn't ever have to specify the device generic.
- This could make BuildOnDevice & ToDevice irrelevant (probably useful in some situations, but not worth keeping for now)

**Comment by coreylowman** [comment]
Another thing that would likely go along with this: moving the device generic to last on tensor (behind tape)

**Comment by ViliamVadocz** [comment]
I think for most use cases you would want to use Cuda if it is available. Maybe there could be a device which uses cuda if it is available, but defaults to Cpu if it is not available?

**Comment by coreylowman** [comment]
At the moment it has to be enabled with the `cuda` feature flag - so if you detect that feature flag is turned on, then that is one way.

I like the idea of auto turning on that feature though so you don't have to specify it by default. There's probably a way to do that in build.rs

**Comment by Narsil** [comment]
Again very personal take, but I don't think having a default device is a good thing.

It's not because you have Cuda that you want to use it, and it's not because you have some computation on Cuda (and so have the feature flag). This is very niche but still.

The other part is readability. To often in pytorch code you have to check if something is indeed on cpu or not (because there is a default on cpu and it's never quite clear if you have actually sent everything where it should.) Not mentioning that because location is so hidden you end up copying tensors unnecessarily. For instance in sd-webui:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5893#issuecomment-1361266783 

If some random code I find on the internet explicitly uses Cuda and for some reason I don't want it,if its explicitly written, it's much easier to modify code than to guess I need to modify compilation feature flag.

**Comment by nkoppel** [comment]
The changed proposed in #412 neuters the dfdx's ability to switch devices or to use multiple devices at runtime, which I think is a bad idea for a few reasons. First, application developers may want to distribute a binary that automatically uses cuda if it is available or that allows the user to choose what device they want to use from the command line. Second, these changes make it very difficult to add support for using multiple cuda devices without breaking existing code. Third, this prevents features like [stable-diffusion-webui's lowvram and medvram options](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings), which swap pieces of a model on and off of vram to run forward propagation on a model that doesn't fit in vram, from being developed.

I don't think that there is a way to have a default device in a way that both ensures access to cuda and checks that tensor operations don't occur between two different devices at compile time. Probably the best way to handle support for multiple devices is to do:

```rust
fn main() {
    if Cuda::is_available() {
        dfdx_main(Cuda::default());
    } else {
        dfdx_main(Cpu::default());
    }
}

fn dfdx_main<D>(device: D) {
    // ...
}
```
We may be able to create a macro to do the above automatically, but this comes at the risk of becoming incompatible with tokio.

**Comment by coreylowman** [comment]
Okay a couple things here:

Having DefaultDevice doesn't necessarily mean you HAVE to use that device - you can still change the generics on tensors & modules, and you can still instantiate a different device at runtime. We can keep the ToDevice/BuildOnDevice/BuildModule changes that I propose reverting in #412 to make the use cases you guys mention easier.

> The other part is readability.  {...snipped...} If some random code I find on the internet explicitly uses Cuda and for some reason I don't want it,if its explicitly written, it's much easier to modify code than to guess I need to modify compilation feature flag.

Thanks for raising this point. I guess in my ideal world we wouldn't even have to specify device generic params on tensors/nn. That is kind of what I was working towards through this issue. The root cause of the issue you point out is having to explicitly set the device generic in the first place. If we didn't have any code that specified the device, then you could freely copy code and it would work regardless of device.

If we could achieve no device generics, that'd be great. I'm skeptical that it's possible in a flexible way that supports all the use cases you guys bring up (e.g. command line setting of device would not be possible).

> Second, these changes make it very difficult to add support for using multiple cuda devices without breaking existing code.

Yeah I was trying to think about this too - definitely want to make this use case as easy as the rest of the devices. I think this will most likely be a separate type of device `MultiDevice<Cuda>`, and if we wanted to make it ergonomic with DefaultDevice, we'd have to likely add a feature flag that changes defaultdevice to this. 🤔

> Third, this prevents features like [stable-diffusion-webui's lowvram and medvram options](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings), which swap pieces of a model on and off of vram to run forward propagation on a model that doesn't fit in vram, from being developed.

I don't think DefaultDevice necessarily prevents it (again not getting rid of the device generics entirely). But this is a good thing to raise as I think this feature is important (and is similar to something @Narsil brought up in discord with using weights that are mmap'd from a file). Will need to think about this further (maybe add some storage generic to the devices like `Cpu<Storage = Ram>`, so you could do `Cpu<Mmap>` or `Cpu<LowVram>`). Probably should ideate in a separate issue for the actual feature, but good to think about in the context of device management.

>  Probably the best way to handle support for multiple devices is to do:

Yeah this is likely the case, I'm not sure how else to get around that.

**Comment by coreylowman** [comment]
> To often in pytorch code you have to check if something is indeed on cpu or not (because there is a default on cpu and it's never quite clear if you have actually sent everything where it should.)

Also I missed this point at first. So this is very in favor of explicitly specifying device generics then?

Maybe the whole issue with these device generics are that they have a default (to Cpu atm). This causes a disconnect because some code may not specify the device, and others might override it.

If all code had to specify device explicitly, it sounds like that may be a net positive?

**Comment by nkoppel** [comment]
We could have no default for device, but that forces users to specify every type parameter, as discussed in #388. Perhaps we could have modules default to a dummy device that throws compile time errors if users try to use it for anything?

**Comment by Narsil** [comment]
> If all code had to specify device explicitly, it sounds like that may be a net positive?

That's my take.

> default to a dummy device

IIUC, this looks like `device="meta"` from pytorch. It would be a compile error instead of a runtime error (which is >> better) but still from a readability standpoint, I think explicit always trumps implicit. In my experience, it's always possible to make explicit hidden, but it's **really** hard to untangle the mess when there's a lot of implicit going on.
A dummy device simply doesn't make any sense. As a newcomer, I would be extremely confused by such an error. Especially if I never used such a dummy device. 

Writing `dfdx` core code, is really complex and daunting, but the rust compiler doesn't allow too much implicit because it **needs** to be guaranteed and so explicit just works. The rust sugar always came later if I understand rust's history correctly. (And don't get me wrong, the sugar is necessary as it's part of what's making rust successful in my eyes, but it comes after solid foundations).

**Comment by coreylowman** [comment]
Okay, so I'm going to remove the defaults for these generics on tensor (pr above) & nn (pr coming in a bit) for now, and will also be adding a Dtype generic to everything in nn (to support things like AMP/f16/f64).

With this change, will probably revisit how to define nn structure ergonomically, since now each thing will have 2 generics. Will open another issue for that after the PRs i mentioned are in.

Closing this default device issue for now.
