### ISSUE TITLE
[Ideation] Allow for different storage types other than RAM in devices

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#413]
First mentioned in #410, right now the Cpu and Cuda device assume tensor data is stored in RAM (heap for Cpu via Vec, and cuda memory for Cuda via CudaSlice).

It'd be nice to enable features like mmap'ing weights from disk, or swapping the tensor data that is in RAM on the fly like stable diffusion allows with its --lowvram options (https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings).

Things to think about:
- Is tensor creation supported with all these methods?
- Is this just a nn level feature?
- What types of storage do we want to support?
- How do they actually work?
    - How do you specify the file/disk location of tensor data?
- How does this interact with devices?

**Comment by nkoppel** [comment]
I think that, ideally, all of these methods should implement `Device<f32>`, using a supertrait named something like LazyDevice, parameterized by a device and a dtype. The implementations of operations should go as follows: 
1. Call a `load` method for each tensor required for the operation, which does nothing if the tensor is already loaded, and otherwise deallocates tensors not needed for the current operation to make room to copy the tensor into working memory.
2. Perform operations using the loaded tensors.
3. Drop unneeded loaded tensors.

Some concerns:
* The implementation will be pretty repetitive, is there any simpler way to do this than implementing every subtrait of Device for LazyDevice?
* How do we detect the amount of memory available, and what strategy do we use to deallocate memory until enough is available? How do we deal with memory fragmentation in this process?
    * What order to remove tensors could be based on size, last use, usage frequency, etc.
    * The way to go may be to drop tensors until we estimate that we have enough space, then repeatedly drop unneeded tensors until we are able to allocate space for the tensor we are trying to load.
* This scheme needs shared mutable state to manage the deallocation of unneeded tensors.

Here's a draft of the data layout for a LazyCuda implementation:
```rust
pub(crate) struct LazyCudaInner {
    cpu: Cpu,
    cuda: Cuda,
    allocated_tensors: BinaryHeap<UniqueId>, // need custom ordering here
    // tensors needed for the current operation
    active_allocated_tensors: HashSet<UniqueId>,
    storages: HashMap<UniqueId, Rc<Option<CudaArray<...>>>>, 
}

pub struct LazyCuda(Rc<RefCell<LazyCudaInner>>);

pub struct LazyCudaStorage<...> {
    cpu_storage: StridedArray<...>,
    cuda_storage: Weak<Option<CudaArray<...>>>>,
    <statistics for ordering>
}
```

**Comment by coreylowman** [comment]
Yeah it'd be awesome if we could add some wrapper type around existing devices, but I'm not sure if that would get rid of all the duplicate impls we'd have to add. It'd be cool if we could do:

```rust
// storage on heap if not enough memory in cuda
let dev: Lazy<Cuda, Cpu> = Default::default();
// or fallback to disk
let dev: Lazy<Cuda, Disk> = Default::default();
```

The biggest complication here if adding a separate type of device (and probably even wrapper type) is: do we need to impl all the kernels for this new device? E.g. maybe the kernel implementations would look like:

```rust
let loaded = self.load_storage(&inp.storage);
self.inner_device.forward(&loaded);
```
instead of
```rust
self.forward(&inp.storage);
```

**Comment by coreylowman** [comment]
Actually a different take: why wouldn't we always want to enable fallback storage?

E.g. 
- when I use CPU, wouldn't a user always want to fallback to disk if tensors don't fit in memory?
- similarly when I use CUDA, it'd be great to always fallback to Cpu storage if I don't have enough cuda memory.

Perhaps when to fallback & how much fallback memory to use could be configurable, but it'd really nice to juts have all this on by default

**Comment by ViliamVadocz** [comment]
> Actually a different take: why wouldn't we always want to enable fallback storage?

I might want to reduce the size of my model if it does not fit in GPU memory for performance. I would like to know when it does not fit. Memory fallback seems like a nice feature to have by default, but I would like to have some way to tell if it is being used (other than inspecting memory use manually).

**Comment by coreylowman** [comment]
Here's a sketch of something where we don't actually do this at the device level. Instead we have a layer on top of Tensor that does this:

```rust
use dfdx::prelude::*;

#[derive(Clone)]
struct LazyTensor<S: Shape, E: Unit> {
    path: String,
    shape: S,
    dtype: E,
}

impl<S: Shape, E: Dtype> LazyTensor<S, E> {
    fn loaded_on<D: Device<E>>(&self, dev: &D) -> Tensor<S, E, D> {
        let f = std::fs::File::open(self.path).unwrap();
        let buffer = unsafe { MmapOptions::new().map(&f).expect("Could not mmap") };
        let tensors = SafeTensors::deserialize(&buffer).expect("Couldn't read safetensors file");
        let mut t = dev.zeros_like(&self.shape);
        t.load_safetensor(&tensors, "wte.weight")
            .expect("Could not load tensor");
        t
    }
}

struct LazyLinear<const I: usize, const O: usize, E: Dtype> {
    weight: LazyTensor<Rank2<I, O>, E>,
}

impl<Batch: Dim, const I: usize, const O: usize, E: Dtype, D: Device<E>>
    Module<Tensor<(Batch, Const<I>), E, D>> for LazyLinear<I, O, E>
{
    type Output = Tensor<(Batch, Const<O>), E, D>;
    type Error = D::Err;
    fn try_forward(
        &self,
        input: Tensor<(Batch, Const<I>), E, D>,
    ) -> Result<Self::Output, Self::Error> {
        let weight = self.weight.loaded_on(input.device());
        input.try_matmul(weight)
    }
}

fn main() {}
```

**Comment by coreylowman** [comment]
Closing this issue out with the intent that the above approach is the way to do this. I've actually successfully done the above approach in llama-dfdx, with a bunch of success! Quite easy to make work and very usable.

I don't think we'll add this to dfdx core *for now* because tensor serialization would be specific to each use case. Definitely open to changing this in the future.
