### ISSUE TITLE
Add EMA (exponential moving average) support for NN

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#425]
This would let you take two models and keep a moving average of them over time.

Potential interfaces would be:
1. `impl Add/Mul<f32>` for layers so you can do `ema = ema * 0.9 + model * 0.1`
2. Add a separate struct to handle this `struct EMA<M>`

**Comment by nkoppel** [comment]
I think it would be even better if we implemented the assignment operators (`+=`, `*=`, etc), for tensors and layers. Then, ema could be implemented as:
```rust
ema *= 1.0 / a -  1.0
ema += model
ema /= 1.0 / a
```
where a is the weight of `model` in the weighted average.

This implementation will save a substantial amount of vram for large models, and would prevent extra allocations.

**Comment by coreylowman** [comment]
Should be very easy to implement this once we can perform ema for tensors with the new visitors api

**Comment by coreylowman** [comment]
Note for future: use the new tensor ema method in BatchNorm2d:

```rust
self.running_mean = self.running_mean.clone() * (E::ONE - self.momentum)
            + mean_chan.retaped::<NoneTape>() * self.momentum;
self.running_var = self.running_var.clone() * (E::ONE - self.momentum)
            + var_chan.retaped::<NoneTape>() * (self.momentum * n / (n - E::ONE));
```

could be

```rust
self.running_mean.ema(mean_chan.retaped::<NoneTape>(), self.momentum);
self.running_var.ema(var_chan.retaped::<NoneTape>() * (n / (n - E::ONE)), self.momentum);
```
