### ISSUE TITLE
Cuda issue: Synchronization problem

### ISSUE THREAD

**Issue by Narsil** [coreylowman/dfdx#464]
Sorry for not being able to run a minimal issue, the bug seems to really stem from a device synchronization issue and not easily replicable in isolation.

Steps to reproduce.

1. `git clone git@github.com:Narsil/fast_gpt2.git`
2. `cd fast_gpt2`
3. `git checkout dfdx`
4. `cargo run --example run --release --features dfdx,cuda` # Incorrect results

5. `cargo run --example run --features intel-mkl --release` Correct results (not dfdx)
6. `cargo run --example run --features dfdx,intel-mkl --release` Correct results (dfdx, cpu)
7. `CUDA_LAUNCH_BLOCKING=1 cargo run --example run --release --features dfdx,cuda`  correct results GPU, with forced synchronization.

Happy to try things to reproduce/pinpoint.

**Comment by coreylowman** [comment]
Thanks for opening, my initial thought is this is caused by creating multiple `Cuda` device objects, which each have their own stream. If so, this is related to https://github.com/coreylowman/cudarc/issues/62.

We can verify by running the following code:

```rust
fn main() {
    let cuda1: Cuda = Default::default();
    let cuda2: Cuda = Default::default();

    let a1 = cuda1.tensor([1.0, 2.0, 3.0]);
    let b1 = cuda1.tensor([2.0, 3.0, 4.0]);

    let a2 = cuda2.tensor([1.0, 2.0, 3.0]);
    let b2 = cuda2.tensor([2.0, 3.0, 4.0]);

    let c1 = a1 + b1; // should be synchronized because its on 1 stream
    let c2 = a2 + b2; // should be synchronized because its on 1 stream

    let d = c1 + c2; // both c1 and c2 are on separate streams, this should have different results?
    println!("{:?}", d);
}
```

**Comment by coreylowman** [comment]
Hmm still not able to reproduce, could be an issue specifically with matmul since cublas uses a explicit setStream call

**Comment by coreylowman** [comment]
All cuda kernels should now be on the default stream, meaning using multiple instances of Cuda will all be synchronized with each other
