### ISSUE TITLE
Non-tensor attributes of nn objects are not saved by SaveToNpz/LoadFromNpz

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#485]
This is currently affecting:
- BatchNorm2D::epsilon
- BatchNorm2D::momentum
- Dropout::p
- LayerNorm1D::epsilon

**Comment by TimerErTim** [comment]
Would it be feasable to store those values as scalar tensor instead and let the `RecursiveWalker` handle the rest upon saving and loading?

**Comment by coreylowman** [comment]
Yeah good idea, very straightforward!
