### ISSUE TITLE
Zero Gradients in highly fragmented functions

### ISSUE THREAD

**Issue by TimerErTim** [coreylowman/dfdx#486]
I have written a minimal working example of this phenomenon: [Zero Gradient Example](https://github.com/TimerErTim/dfdx_nogradient_example).

Basically the gradients seem to completely diminish as the model learns to reproduce slightly random output from completely random input. 
Now this may be an error in my model design or just a major coincidence as I test the gradients by summing up all model gradients and checking if that sum is equal to zero. It could also be that model indeed found a local minima for all possible samples, but as I used unbatched SGD this seems very unlikely. 

Maybe one of you more experienced people could have a look at the example to either point out my error or confirm that this is indeed an issue.

**Comment by TimerErTim** [comment]
I am crying right now... as often one finds the solution shortly after he posted the problem.

Seems that the `ReLU` on the output layer caused zero gradients due to it's clipping of negative values. With that activation function removed, the example does not produce zero gradients anymore. I am letting this issue open in case someone has something to add to this topic.

**Comment by coreylowman** [comment]
Hahaha classic 🤣 I'll close this in a bit
