### ISSUE TITLE
Bug: Binary operations do not always merge tapes in the correct order.

### ISSUE THREAD

**Issue by nkoppel** [coreylowman/dfdx#507]
Consider the following example of a simple network with a SplitInto layer that recombines outputs to get its loss:
```rust
type Mlp = (
    (Linear<2, 2>, ReLU),
    SplitInto<(Linear<2, 1>, Linear<2, 1>)>
);

let model = dev.build_module::<Mlp, f32>();

let (o1, o2) = model.forward(dev.sample_normal::<Rank1<2>>().trace());
let grad1 = (o2.sum() * 0. + o1.trace().sum()).backward();

let (o1, o2) = model.forward(dev.sample_normal::<Rank1<2>>().trace());
let grad2 = (o1.trace().sum() + o2.sum() * 0.).backward();
```

`grad2` will not contain zero gradients for the first linear layer (`model.0.0`), while `grad1` will contain nonzero gradients for the same layer. This is because '+' places the backward operation of the sum of o1 *before* the backward operations held in o2's tape, meaning that the error term from o1 is not propagated backwards to any of the linear layers in the model. To me, this is highly unintuitive, and may be the issue preventing #437 from training properly.

One way to fix this is to allow tapes to be cloned, which would require the following changes:
* Remove Gradients field from OwnedTape and defer allocation of gradients until 'backward' is called
* Store operations in tapes as `Rc<dyn Fn(...) -> ...>` to allow them to be cloned
* Merge OwnedTapes by adding adding all operations from the second tape not already in the first tape to the end of the first tape.
* Change the implementation of SplitInto and change/remove some tensor methods related to tapes to reflect the above changes.

One substantial downside to this system is that it allows users to make unnecessary computations, like ignoring some outputs of SplitInto or calling 'backward' more than once for a single pass through a model. A partial solution to this would be to defer all tensor operations to when they are needed, such as the user calling 'array', 'backward', or printing a certain tensor. Unfortunately, doing this would be quite complicated, and may make the library's behavior less intuitive.

Another solution that would not involve cloning tapes could involve storing a list of "ancestor operations", or operations that occurred one operation before the current tensor had its tape removed. These "ancestor operations" could be used to determine which order to append operations, though I am not fully sure how to implement this.

**Comment by nkoppel** [comment]
For the tape cloning idea, we could implement `OwnedTape::merge` by storing backward operations in a hashable wrapper type and storing them in an [IndexSet](https://docs.rs/indexmap/latest/indexmap/set/struct.IndexSet.html).

**Comment by coreylowman** [comment]
Thanks for raising this.

For ancestry, could include a globally incrementing counter (`unique_id()`) along with each operation, and then merge could sort the operations based on that?

**Comment by coreylowman** [comment]
Yeah this seems to fix the issue:

```diff
diff --git a/src/gradients.rs b/src/gradients.rs
index 24e912d..7412b69 100644
--- a/src/gradients.rs
+++ b/src/gradients.rs
@@ -5,7 +5,7 @@ use std::collections::HashMap;
 use std::{boxed::Box, vec::Vec};

 use crate::tensor::storage_traits::{AllocGrad, DeviceStorage};
-use crate::unique_id::{HasUniqueId, UniqueId};
+use crate::unique_id::{unique_id, HasUniqueId, UniqueId};

 /// A generic container for keeping variable sized arrays associated with a [UniqueId].
 ///
@@ -187,7 +187,10 @@ impl Gradients {
 /// This would not be possible if these chain rule operations were inside of GradientTape!
 #[allow(clippy::type_complexity)]
 pub struct GradientTape<D: DeviceStorage> {
-    operations: Vec<Box<dyn FnOnce(&mut Gradients) -> Result<(), D::Err>>>,
+    operations: Vec<(
+        UniqueId,
+        Box<dyn FnOnce(&mut Gradients) -> Result<(), D::Err>>,
+    )>,
     gradients: Gradients,
 }

@@ -220,14 +223,14 @@ impl<D: DeviceStorage> GradientTape<D> {
         &mut self,
         operation: F,
     ) {
-        self.operations.push(Box::new(operation));
+        self.operations.push((unique_id(), Box::new(operation)));
     }

     /// Compute the [Gradients]! This just runs all the operations on a new [Gradients] struct.
     ///
     /// Note that this method takes ownership of self, so it can't be called twice!
     pub(crate) fn execute(mut self) -> Result<Gradients, D::Err> {
-        for operation in self.operations.drain(..).rev() {
+        for (_, operation) in self.operations.drain(..).rev() {
             (operation)(&mut self.gradients)?;
         }
         Ok(self.gradients)
@@ -239,6 +242,7 @@ impl<D: DeviceStorage> GradientTape<D> {
             .gradient_by_id
             .extend(other.gradients.gradient_by_id.drain());
         self.operations.append(&mut other.operations);
+        self.operations.sort_by_key(|(k, _)| *k);
     }
 }
```

when printing the grads from your example:
```rust
StridedArray { data: [-0.35925025, 0.14855795, 0.0, 0.0], shape: (Const, Const), strides: [2, 1] }
StridedArray { data: [0.24250603, 0.0], shape: (Const,), strides: [1] }
StridedArray { data: [-0.35925025, 0.14855795, 0.0, 0.0], shape: (Const, Const), strides: [2, 1] }
StridedArray { data: [0.24250603, 0.0], shape: (Const,), strides: [1] }
```

**Comment by coreylowman** [comment]
Actually I think we can just get away with sorting once at the beginning of `execute`, instead of at merge time. That should not be an issue
