### ISSUE TITLE
Consider replacing `dfdx::Module` with `tower::Service` or adding an adaptor

### ISSUE THREAD

**Issue by LegNeato** [coreylowman/dfdx#516]
As mentioned in the README, a lot of`dfdx`'s magic is enabled by the `Module` trait:

```rust
pub trait Module<Input> {
    /// The type that this unit produces given `Input`.
    type Output;
    type Error: core::fmt::Debug;

    fn try_forward(&self, input: Input) -> Result<Self::Output, Self::Error>;

    /// Forward `Input` through the module and produce [Module::Output].
    ///
    /// **See [ModuleMut::forward_mut()] for version that can mutate `self`.**
    fn forward(&self, input: Input) -> Self::Output {
        self.try_forward(input).unwrap()
    }
}
```

This is _extremely_ close to [`tower::Service`](https://docs.rs/tower/latest/tower/trait.Service.html):

```rust
pub trait Service<Request> {
    /// Responses given by the service.
    type Response;
    type Error;

    /// The future response value.
    type Future: Future<Output = Result<Self::Response, Self::Error>>;

    /// Returns `Poll::Ready(Ok(()))` when the service is able to process requests.
    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>>;

    /// Process the request and return the response asynchronously.
    fn call(&mut self, req: Request) -> Self::Future;
}
```

It might be useful to combine the two ecosystems and share `Services` and `Layers` where [behavior is generic](https://docs.rs/tower/latest/tower/index.html#modules). CUDA is async I believe so perhaps it would be good to go all in on async? Furthermore, `Modules` could become network transparent / distributed more easily if they plugged into the tower ecosystem, and as `hyper` [supports tower](https://docs.rs/hyper/1.0.0-rc.3/hyper/service/index.html) it might feel natural to slot in dataset downloading in the same programming paradigm. It could also enable cool things like [tracing deep learning execution](https://github.com/tokio-rs/tracing) or an [LSP for dfdx](https://github.com/ebkalderon/tower-lsp).

**Comment by coreylowman** [comment]
Hey thanks for the suggestion! I agree they do seem very close, and there could be a nice adapter between them. I'm pretty much set on "synchronously" using cuda though, as moving to async at this point would be a ton of effort.

Totally open to contributions to cudarc with an async api, if someone wants to work on that!

I think the adapter is a good idea, but that would belong outside of core dfdx to make it easier to provide the UX for tower that it'd probably need.

Closing for now, but thanks for the suggestion! 🚀
