### ISSUE TITLE
Use the winograd convolution algorithm when possible

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#527]
See https://medium.com/@dmangla3/understanding-winograd-fast-convolution-a75458744ff for beginner details.

https://arxiv.org/abs/1509.09308 is the paper
> Deep convolutional neural networks take GPU days of compute time to train on large data sets. Pedestrian detection for self driving cars requires very low latency. Image recognition for mobile phones is constrained by limited processing resources. The success of convolutional neural networks in these situations is limited by how fast we can compute them. Conventional FFT based convolution is fast for large filters, but state of the art convolutional neural networks use small, 3x3 filters. We introduce a new class of fast algorithms for convolutional neural networks using Winograd's minimal filtering algorithms. The algorithms compute minimal complexity convolution over small tiles, which makes them fast with small filters and small batch sizes. We benchmark a GPU implementation of our algorithm with the VGG network and show state of the art throughput at batch sizes from 1 to 64. 

There are a ton of articles on this!

**Comment by M1ngXU** [comment]
is there a plan to use cudnn for this?

**Comment by coreylowman** [comment]
Depends on how complex it is to implement and what speedups cudnn could give us

**Comment by M1ngXU** [comment]
shouldn't be that hard (check out my cudnn pr on cudarc :D), but not sure about the speed ups, though i think that cudnn is quite optimized

**Comment by coreylowman** [comment]
Okay yeah I agree, I don't think we should add winograd directly to dfdx. Instead once #638 is done, we can optionally use the winograd option in cudnn.
