### ISSUE TITLE
Compilation hanging with dynamic dimensions

### ISSUE THREAD

**Issue by jafioti** [coreylowman/dfdx#554]
I've been switching my language model project over to using dyn dims for batch size and seq len, and for an unknown reason compilation hangs and leaks memory. I also get an error when running rust-analyzer due to an nvcc error, but that's a seperate concern.

I've created a reproduction here: https://github.com/jafioti/dfdx_issue

Just clone it and try to build.

**Comment by coreylowman** [comment]
MHA doesn't support dynamic dimensions right now. It seems related to that cause if I swap it to using const dims it compiles fine. Maybe rust is searching for an impl somehow?

**Comment by coreylowman** [comment]
With recent changes to matmul & reshape, I'm moving transformer off nightly & also accepting dyn dimensions, woohoo!!
