### ISSUE TITLE
Add convienence `AutoDevice` type alias based on features

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#563]
This would essentially pull all the device snippets that are used in examples into dfdx core as a utility type:
```rust
/// Cuda if feature is enabled, otherwise Cpu
#[cfg(not(feature = "cuda"))]
pub type AutoDevice = Cpu;

/// Cuda if feature is enabled, otherwise Cpu
#[cfg(feature = "cuda")]
pub type AutoDevice = Cuda;
```

Then downstream user code could just use this unless they want more control over devices.

TODOS:
1. Add the above type aliases to `src/tensor/mod.rs`
2. Update all the `examples/` (**except 01-tensor.rs**) to use this AutoDevice instead of the device type aliases. We want to keep 01-tensor using the type aliases just to show the basics.

**Comment by Alexandcoats** [comment]
It would also be really nice for usability if you could set a default device for everything (a static somewhere) and remove the need to explicitly use to for most operations.

**Comment by kstavro** [comment]
@coreylowman Great seeing the use of the new starter friendly tag, that really helps!
