### ISSUE TITLE
Gradient Averaging

### ISSUE THREAD

**Issue by jafioti** [coreylowman/dfdx#567]
Right now it's possible to accumulate gradients, though I believe they are directly added. This means gradients can add up to be quite large when used in an update. A better alternative (or just another option) would be to be able to average them before using them to update. I think simply allowing gradients to be divided by a scalar (the number of accumulations) should allow for basically the same API.

**Comment by coreylowman** [comment]
This should be possible by just dividing the loss by the number of accumulations before calling backward. Is that sufficient, or do you think there should be a separate way to do this?

Semi-related is gradient clipping, which will need a method on Gradients for.
