### ISSUE TITLE
Add upsample and conv-transpose operations

### ISSUE THREAD

**Issue by Cifram** [coreylowman/dfdx#574]
In order to support a UNet architecture, used my many generative models for images, there needs to be a way to increase the tensor resolution. The common ways to do this are the convolution transpose operation, or the upsample operation. Sadly, dfdx supports neither of these right now.

It's possible, with some work, to construct a simple nearest-neighbor upsample with an integer increase with the select operation, but doing so is not intuitive or easy, and doesn't seem like it'd be very efficient.

While not needed for UNets specifically, PyTorch also supports upsamples by fractional values, such as increasing the resolution by 1.6x. This would pose a significant challenge for the dfdx architecture with it's hardcoded tensor dimensions, as I don't think it's possible to do the necessary math with const generics to statically determine the dimensions of the output tensor.

**Comment by coreylowman** [comment]
Luckily we have runtime dimensions now, so I think this would be pretty straightforward

**Comment by Cifram** [comment]
Oh, excellent. I see you just pressed a new release today. I was still running on v0.10.

**Comment by sirandreww** [comment]
Is there an example on using runtime dimensions and a guideline about when to use it?

**Comment by opfromthestart** [comment]
I would be interested in working on conv-transpose. I don't know much about cuda but I think I could get a cpu forward implementation working, but I'm not familiar with how the backward is working (I'm familiar with calculus but not as much with matrix calculus). I assume it should have the layer struct as `src/nn/conv-transpose.rs` and then the actual ops at `src/tensor-ops/conv-transpose/[mod|cpu_kernel].rs`.

**Comment by coreylowman** [comment]
> Is there an example on using runtime dimensions and a guideline about when to use it?

@sirandreww there's some uses in examples/01-tensor.rs. Would be happy to accept contributions on adding more uses to examples if you want to contribute some! All the tensor ops (except conv2d at the moment) support runtime dimensions, though the shapes are checked at runtime instead of compile time.

> I would be interested in working on conv-transpose. I don't know much about cuda but I think I could get a cpu forward implementation working, but I'm not familiar with how the backward is working (I'm familiar with calculus but not as much with matrix calculus). I assume it should have the layer struct as src/nn/conv-transpose.rs and then the actual ops at src/tensor-ops/conv-transpose/[mod|cpu_kernel].rs.

Awesome! Yeah I can help out too, conv2d is one of the more complex ops we have due to the shape calculations/how it's implemented.

It should mirror src/tensor_ops/conv2d fairly closely. Note that the current conv2d implementation folds the input/output into patches so that we can use fast matrix multiplication. I suspect you can probably re-purpose a lot of the existing code for conv transpose

**Comment by coreylowman** [comment]
Good to know, I'll have to look into conv transpose more.

Lmao about pytorch, their kernels/internals are a huge mess, I'm glad I'm not the only one who has trouble finding stuff in there 😀 I have had *slightly* more success finding tensorflow kernels, but I couldn't find transpose from a quick skim

**Comment by Cifram** [comment]
Fur what it's worth, I think the upsample operation is actually more useful, and it's much simpler. If I were to have one or the other, that's the one I'd want.

A lot of people still use transpose convolutions for UNets, because it's the classic way to do it, but they tend to create checkerboard artifacts in the resulting image. Doing a nearest neighbor upsample followed by a "same" convolution gets similar results without the checkerboard.

**Comment by Cifram** [comment]
Probably too late to be useful, since it seems the new upsample is mostly ready to push already... But while waiting, I attempted to implement my own nearest neighbor upsample module, just using existing tensor operations so I'd get cuda and backprop for free. I doubt it's the most efficient thing, but it's pretty simple:

```
use dfdx::prelude::*;

#[derive(Default)]
pub struct Upsample<const SCALE: usize>;

impl<const SCALE: usize> ZeroSizedModule for Upsample<SCALE> {}
impl<const SCALE: usize> NonMutableModule for Upsample<SCALE> {}

impl<
		const SAMPLES: usize,
		const CHANNELS: usize,
		const W: usize,
		const H: usize,
		const SCALE: usize,
		E: Dtype,
		D: Device<E>,
		T: Tape<E, D>,
	> Module<Tensor<Rank4<SAMPLES, CHANNELS, W, H>, E, D, T>> for Upsample<SCALE>
where
	[(); W * SCALE]:,
	[(); H * SCALE]:,
{
	type Output = Tensor<Rank4<SAMPLES, CHANNELS, { W * SCALE }, { H * SCALE }>, E, D, T>;
	type Error = <Cuda as HasErr>::Err;

	fn try_forward(&self, input: Tensor<Rank4<SAMPLES, CHANNELS, W, H>, E, D, T>) -> Result<Self::Output, Self::Error> {
		let output: Tensor<Rank5<SAMPLES, CHANNELS, W, H, SCALE>, E, D, T> = input.broadcast();
		let output: Tensor<Rank4<SAMPLES, CHANNELS, W, { H * SCALE }>, E, D, T> = output.reshape();
		let output = output.permute::<_, Axes4<0, 1, 3, 2>>();
		let output: Tensor<Rank5<SAMPLES, CHANNELS, { H * SCALE }, W, SCALE>, E, D, T> = output.broadcast();
		let output: Tensor<Rank4<SAMPLES, CHANNELS, { H * SCALE }, { W * SCALE }>, E, D, T> = output.reshape();
		let output = output.permute::<_, Axes4<0, 1, 3, 2>>();
		Ok(output)
	}
}
```

The key is that I realized I can duplicate the values in the final dimension by broadcasting a new dimension on the end, and then reshaping the flatten that back into the final dimension. So it does that for the final dimension, then permutes to swap the last two dimensions, does it for the final dimension again, then permutes back.

**Comment by coreylowman** [comment]
That's pretty clever, nice workaround!
