### ISSUE TITLE
Add Conv2D groups

### ISSUE THREAD

**Issue by Cifram** [coreylowman/dfdx#589]
See the `groups` parameter on PyTorch's Conv2D module: https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html

This turns out to be necessary to implement the efficient depthwise/pointwise convolution used by MobileNet.

**Comment by Awpteamoose** [comment]
Was trying to implement MobileNet, hit this today. Seems like a popular technique for fast/small convnets.

**Comment by coreylowman** [comment]
Added to tracking issue for next release. Will be good to bundle this & the dilation option together
