### ISSUE TITLE
`reshape` does not work on tensors of type `usize`

### ISSUE THREAD

**Issue by Cifram** [coreylowman/dfdx#591]
When I attempt to run this line:
```
let upsample_gather: Tensor<Rank1<{ SIZE * 2 }>, usize, Cuda> = upsample_gather.reshape();
```
I get this error:
```
error[E0599]: the method `reshape` exists for struct `Tensor<(Const<SIZE>, Const<2>), usize, Cuda>`, but its trait bounds were not satisfied
  --> src\upsample.rs:28:83
   |
28 |         let upsample_gather: Tensor<Rank1<{ SIZE * 2 }>, usize, Cuda> = upsample_gather.reshape();
   |                                                                                         ^^^^^^^ method cannot be called on `Tensor<(Const<SIZE>, Const<2>), usize, Cuda>` due to unsatisfied trait bounds
   |
  ::: C:\Users\heruf\.cargo\registry\src\index.crates.io-6f17d22bba15001f\dfdx-0.11.0\src\tensor\tensor_impls.rs:32:1
   |
32 | pub struct Tensor<S: Shape, E: Unit, D: DeviceStorage, T = NoneTape> {
   | -------------------------------------------------------------------- doesn't satisfy `_: ReshapeTo`
   |
  ::: C:\Users\heruf\.cargo\registry\src\index.crates.io-6f17d22bba15001f\dfdx-0.11.0\src\tensor\cuda\device.rs:14:1
   |
14 | pub struct Cuda {
   | --------------- doesn't satisfy `_: ReshapeKernel<usize>`
   |
   = note: the following trait bounds were not satisfied:
           `usize: Dtype`
           which is required by `dfdx::tensor::Tensor<(Const<SIZE>, Const<2>), usize, dfdx::tensor::Cuda>: dfdx::tensor_ops::ReshapeTo`
           `dfdx::tensor::Cuda: tensor_ops::reshape_to::ReshapeKernel<usize>`
           which is required by `dfdx::tensor::Tensor<(Const<SIZE>, Const<2>), usize, dfdx::tensor::Cuda>: dfdx::tensor_ops::ReshapeTo`
```
Before that line, `upsample_gather` has type `Tensor<(Const<SIZE>, Const<2>), usize, Cuda>`.

It appears `Dtype` is only implemented for `f32` and `f64`. I'm not sure what the exact intent of `Dtype` is. If it's supposed to cover all the data types that can go into a tensor, then it should be implemented for all the other types that tensors now support. If it's intended to tag specifically floating point types, then `reshape` should be updated to not require `Dtype`, because `reshape` doesn't do any arithmetic on the contents of the tensor, so shouldn't need to care what data type it stores.

**Comment by coreylowman** [comment]
Dtype is intended to be any type that can do a backward pass with gradients (which is for now floating point numbers), and Unit is intended to be any type that a tensor can hold.

I see the need though, will think about this

**Comment by coreylowman** [comment]
Notably, during inference we can do forward pass without requirement of doing backward pass. Additionally for quantization, we need to support some operations with integer dtypes

**Comment by Cifram** [comment]
For my immediate use case, I just needed to flatten a 2D tensor into a 1D tensor, so I was able to work around it by doing `device.tensor(upsample_gather.as_vec())`. But that's very specific to this case. And would also break back propagation, if that mattered, but since this is just the tensor for defining a gather operation, it shouldn't need back prop.

**Comment by nkoppel** [comment]
Resolved by #602.

**Comment by coreylowman** [comment]
I don't think it's actually resolved - the reshape traits & methods on tensor still require Dtype don't they?

**Comment by nkoppel** [comment]
Whoops, forgot to change that, this can be resolved by changing `Dtype` to `Unit` on lines 8 and 76 of `reshape_to/mod.rs`

**Comment by coreylowman** [comment]
This is a larger issue with all the data movement kernels - I could see people wanting to use broadcast/permute/etc on non float tensors when gradients aren't being tracked.

From the kernel trait level we could just make the top level `Unit` and then add `where E: Dtype` for backward. Then for the tensor methods/traits we'd have one impl for Dtype that calls fwd & bwd, and one impl for Unit that just calls fwd
