### ISSUE TITLE
Binary ops on two tensors with different dim types

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#594]
I'd like to be able to do the following in dfdx:

```rust
let a: Tensor<(Const<10>, usize, Const<3>, usize), f32, _> = dev.zeros_like(&(Const, 5, Const, 4));
let b: Tensor<(Const<10>, Const<5>, usize, usize), f32, _> = dev.zeros_like(&(Const, Const, 3, 4));
let c: Tensor<(Const<10>, Const<5>, Const<3>, usize), f32, _> = a + b;
```

Notably:
- dim 0 would be able to be type checked at compile time
- dims 1-3 would have to be checked at runtime since they aren't the same type.
- (nice to have) dims 1 & 2 on `c` can be the const dims from a & b - they have been elevated to compile time.

**Comment by jafioti** [comment]
Shouldn't this be a falliable operation? Because the dyn dims might not match up, so there's no guarantee this won't panic

**Comment by coreylowman** [comment]
Currently all runtime operations panic if the dimensions don't match up (so fallibility is just used for memory allocates).

If we want to move shape checks to be Err, we should discuss in a separate issue.

**Comment by jafioti** [comment]
Isn't this possible with `realize` and `unwrap`? To realize the dyn dims as const dims and unwrap it, which would panic if the sizes didn't match

**Comment by coreylowman** [comment]
Oh yeah good point `a + b.realize().unwrap()` does work for this! We should add this to examples/02-ops. I'll add to #593
