### ISSUE TITLE
Fix no-std support

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#613]
Related to #612 

A few recent PRs are not no_std compatible. You can see the issues by running `cargo check --all --no-default-features -F no-std`.

This issue should go through and fix the issues found with the command above. It should mainly be imports

**Comment by Alexandcoats** [comment]
This one is actually going to be kind of tough without excluding a lot of functionality from no-std environments.

**Comment by coreylowman** [comment]
What are you referring to? We require alloc support with no-std, so Vec/BTreeMap/String are all available, you just have to actually import them in no-std. I think some things like `.to_string()` might not exist, but you can use `.into()` for those iirc

**Comment by Alexandcoats** [comment]
Ah, nevermind then.
