### ISSUE TITLE
`ConcatKernel` trait not required by `Device` trait

### ISSUE THREAD

**Issue by Cifram** [coreylowman/dfdx#627]
The `ConcatKernel` trait is implemented for both `Cpu` and `Cuda`, but because it's not required by the `Device` trait, like most of the other kernels are, the `concat` function can't be called in contexts that have a generic `Device`. And because all the kernel traits aren't public, it can't be explicitly required by any such generic context outside this crate, making it actually impossible to make a custom module that calls `concat` while being generic over the device.

**Comment by nkoppel** [comment]
This is fixed on main by #621, but hasn't made it to a release yet.

**Comment by coreylowman** [comment]
I'll be cutting a patch release soon with all the recent updates!

**Comment by Cifram** [comment]
Ah, sorry! Should have checked the current code before making an issue.
