### ISSUE TITLE
Use cuDNN for conv2d

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#638]
Now that Cuda has a workspace method, it's possible to use cuDNN to speed up convolutions. The work for this should be:

1. Add a `cudnn` feature to dfdx `cudnn = ["cuda", "cudarc/cudnn"]`
2. In conv kernel forward & backward, if cudnn feature is active, invoke the cudnn API calls, otherwise keep the existing methods.

Note that currently cudarc doesn't have a safe cudnn API, so this may have to use straight sys/result calls for now. Part of this issue can be contributing back to cudarc as well.

**Comment by M1ngXU** [comment]
> "cudarc?/cudnn"

what does this question mark mean? optional? (isn't cuda being used anyway?)
