### ISSUE TITLE
Enable upscale2d on runtime dimensions

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#642]
This will involve a bit of rewrite of the Upscale2D traits to use `Dim` and `ConstDim`, similar to how Broadcast is implemented

**Comment by coreylowman** [comment]
@opfromthestart @nkoppel either of you have any interest in this one? Otherwise I can

**Comment by nkoppel** [comment]
It won't be quite as easy as conv2d/convtrans2d because the output dimensions can't be inferred, but I'll take a shot at this. Upscale also needs documentation.

**Comment by coreylowman** [comment]
Yeah we can stick with opfromthestart's approach of passing the dimensions in. I'm imagining:

```rust
t.upscale2d(); // const case
t.upscale2d_like(height, width); // runtime case
```
