### ISSUE TITLE
Upscale2D or Conv2D produces NaN values

### ISSUE THREAD

**Issue by nkoppel** [coreylowman/dfdx#677]
My application using dfdx: https://github.com/nkoppel/generals-bot is currently failing to train a unet to play generals.io because the [policy network](https://github.com/nkoppel/generals-bot/blob/072bb025c4ce67b5e5756fa0878bcb4f8677c8e5/src/bots/ppgnet.rs#L80) produces NaN values during training. This is probably a bug in Conv2D or Upscale2D, as the NaN values only occupy a small area of the output, and this program has successfully trained networks without Upscale2D. The NaN values occur about every 100-500 batches, and appear only in the last image of a batch, in the following shape:

```
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 NaN
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 NaN
NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
``` 
(along the bottom and the bottom 3 of the right edge, for all 4 output channels)

Due to its relative rarity and the consistency of the shape of the NaN values, I suspect that this is a bug due to Conv2D or Upscale2D reading uninitialized memory or failing to write to uninitialized memory, but I have been unable to locate the bug thus far. It is probably more likely to be a bug in Upscale2D, because I have tried using the new cudnn implementation of Conv2D, and experienced the exact same behavior.

This error is reproduced here: https://gist.github.com/nkoppel/db07f684222a7169d2c39b205542d4c5. I have no idea why, but using Sgd or inspecting the value of `out` both prevent the bug from occurring.

**Comment by coreylowman** [comment]
Is this with `cudnn` or `cuda`?

**Comment by coreylowman** [comment]
Do you happen to have the image sizes that upscale is scaling to? I'm wondering if 
```c++
float h_scale = ((float)op.h_in-1)/(op.h_out-1);
float w_scale = ((float)op.w_in-1)/(op.w_out-1);
```
is producing nans, but that would require h_out/w_out to be `1`

**Comment by nkoppel** [comment]
I suspect that this bug is memory-related, and it being difficult to reproduce is due to the pseudo-randomness in cuda's malloc algorithm.

**Comment by coreylowman** [comment]
Also, this happens in the forward call right? Not backward?

**Comment by nkoppel** [comment]
Yes, at least within my application, it happens in the forward call. If it had happened in the backward call, parameters would have been set to NaN and caused the entire output to be NaN.

**Comment by coreylowman** [comment]
The weird thing is since upscale2d calls `let mut out = inp.device.try_zeros_like(&(chan, out_height, out_width))?;`, this will memset all the data in the output to 0. Meaning the kernel is definitely setting the nan values.

**Comment by nkoppel** [comment]
Yes, and it seems impossible for upscale2d to read out of bounds as long as the data in `op` and `inp_strides` is correct.

**Comment by coreylowman** [comment]
Oh I figured it out - there's a bug in the upscale2d kernel. Will push to the above PR
