### ISSUE TITLE
Dilation for Conv2d and MaxPool2d ? 

### ISSUE THREAD

**Issue by xgillard** [coreylowman/dfdx#693]
Hi, 

I know it feels a bit cliché but I'd really like to thank you for the hard work on this crate ! 

I am currently trying to replicate CSRNet in rust using dfdx (
paper  : https://openaccess.thecvf.com/content_cvpr_2018/papers/Li_CSRNet_Dilated_Convolutional_CVPR_2018_paper.pdf
source: https://github.com/leeyeehoo/CSRNet-pytorch ). So far I can manage my way through the lib but I am facing the problem where the pytorch implem permits the use of **dilated** convolution rather than plain conv. Do you think that dilated conv could be added to the library ? 

In pytorch, it is the "dilation" parameter that is present in the conv2d and maxpool2d classes:
* https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html
* https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html

As I know dilated convolution might seem a bit convoluted (pun intended 🙃) at first, here is a page that clearly shows what it does: https://github.com/vdumoulin/conv_arithmetic/blob/master/README.md

**Comment by coreylowman** [comment]
Thank you! Yeah this is a good request, thanks for opening - dilation seems pretty straightforward to implement (at least compared to some other conv options). It will cause some breaking changes to the API though (adding a new generic parameter), so merging the change into main might be delayed a bit.

**Comment by xgillard** [comment]
Wow, I did not expect you to be SO reactive ! Thanks for considering the feature. 
I definitely understand that this would be breaking b/c of the new generics.. and I'm totally okay with a bit of delay before merging to main + conv2d and maxpool2d are still nightly though so I suppose it's still fair not to expect them to be stable.

**Comment by coreylowman** [comment]
Haha yeah I try to keep an eye on my github notifications! 👍Will definitely be a good add to dfdx though

**Comment by M1ngXU** [comment]
just saw this issue via the new tracking issue; cudnn has a diletation parameter so we could just use that for now

**Comment by coreylowman** [comment]
Yep will be trivial with cudnn! The biggest part will be:
1. adding to Cpu/non-cudnn kernels
2. Adding dilation parameter at nn level
I suspect the first will be the biggest change.

**Comment by M1ngXU** [comment]
Maybe just support cuDNN for now? Like a special cudnnconv struct? if you are using cuda/cuDNN, you could use that for now @xgillard
