### ISSUE TITLE
f32 stddev is too far from numpy

### ISSUE THREAD

**Issue by iacore** [coreylowman/dfdx#703]
It does not match pytorch or numpy's result.

https://github.com/iacore/debug-dfdx-stddev

**Comment by coreylowman** [comment]
Hello, we have this in the documentation, but it's a bit hard to find. The pytorch equivalent is `t.std(Axes, unbiased=False)`. So variance & stddev is unbiased version here.

Will close for now - if you want to open a separate issue requesting biased stddev/variance, feel free!

**Comment by iacore** [comment]
I've updated the example to not use .stddev

I'm quite sure

1. this is a bug
2. `.stddev` still divide by N, not N-1

**Comment by coreylowman** [comment]
I get:
| | val|
| --- | --- |
| dfdx | 0.29048672 |
| np | 0.29048681259155273 |
| pytorch | 0.29048684 |

which are all within `1e-6` of each other.

If I convert everythign to use f64 I get:
| | val|
| --- | --- |
| dfdx| 0.29048683138535825 |
| np | 0.2904868313853555 |
| pytorch | 0.29048683138535825 |

where notably dfdx and pytorch are equivalent.

**Comment by coreylowman** [comment]
Can you repro the above numbers? With np you can add `a = a.astype(np.float64)` after initialization to convert to f64, and then in dfdx you can call

```rust
let std = a.to_dtype::<f64>().stddev(0.0);
```

**Comment by iacore** [comment]
> I get:
> 	val
> dfdx 	0.29048672
> np 	0.29048681259155273
> pytorch 	0.29048684
> 
> which are all within `1e-6` of each other.
> 
> If I convert everythign to use f64 I get:
> 	val
> dfdx 	0.29048683138535825
> np 	0.2904868313853555
> pytorch 	0.29048683138535825
> 

I got those values as well.

I have made RWKV with dfdx: https://git.envs.net/iacore/rwkv-rs

However, the value drift too far from numpy/pytorch after 1 pass of the network. (has 26 stddev).

**Comment by coreylowman** [comment]
Thanks for sharing the code! Any ideas of other places the issue could be? I'm pretty confident stddev is implemented correctly based on the numbers, so the issue is probably somewhere else

**Comment by iacore** [comment]
> Any ideas of other places the issue could be?

No idea.

I've traced the values across neural network. The value drift bit by bit until it's completely unusable.

**Comment by iacore** [comment]
I've added the arraymancer (Nim) impl. It's same as dfdx.
