### ISSUE TITLE
Add matmul(matrix, vector)

### ISSUE THREAD

**Issue by iacore** [coreylowman/dfdx#706]
Here's the code for it.

```rust
use dfdx::prelude::*;
use Tensor1D as V;
use Tensor2D as M;

fn matmul<const N0: usize, const N1: usize>(lns: M<N0, N1>, rhs: V<N1>) -> V<N0> {
    let rhs = rhs.reshape::<Rank2<N1, 1>>();
    let res: M<N0, 1> = lns.matmul(rhs);
    res.reshape()
}
```

**Comment by coreylowman** [comment]
This should be fairly close in implementation to the vector * matrix implementation. Any interest in contributing this? I can help out with the cuda stuff

**Comment by iacore** [comment]
I looked at here: https://github.com/coreylowman/dfdx/tree/main/src/tensor_ops/matmul

The problem is that I don't understand the complex type class or how to use `sgemm`. Is it good enough to use `Tensor::reshape` in my impl?

**Comment by coreylowman** [comment]
Oh thanks for that suggestion, ended up simplifying other implementations as well! 🥂
