### ISSUE TITLE
Impl Built for (T,)

### ISSUE THREAD

**Issue by opfromthestart** [coreylowman/dfdx#724]
Often when modifying the structure of a network I get something like
```
(
    (
        ... stuff...
    ),
),
...
```
in my type, which doesnt build. Adding this would be nice. Ill probably do a PR soon.

**Comment by coreylowman** [comment]
Good add. We'll also need to impl Module/impl ModuleMut for tuples of size 1

**Comment by opfromthestart** [comment]
I added it to the existing macro which has those as well.

**Comment by coreylowman** [comment]
Sweet, this is closed by #725
