### ISSUE TITLE
Tensor Ops - 1D Convolution

### ISSUE THREAD

**Issue by mert-kurttutan** [coreylowman/dfdx#728]
Hi,
I could not see the implementation of 1D Convolution. Is it not implemented in the library, or am I missing it ?

**Comment by opfromthestart** [comment]
It is not yet implemented. What is the model architecture that you are using a 1D Convolution in, just out of curiosity?

**Comment by mert-kurttutan** [comment]
Wav2vec2 type of architecture. But, more generally, conv1d is present a lot of the audio models.
