### ISSUE TITLE
Get size of tensor

### ISSUE THREAD

**Issue by sirandreww** [coreylowman/dfdx#729]
With the introduction of runtime dimensions there should be a simple way to get the shape of a tensor.
I imagine this would be similar to:
https://pytorch.org/docs/stable/generated/torch.Tensor.size.html

```rust
let a: Tensor<(usize, usize), f32, _> = dev.zeros_like(&(2, 3));
assert_eq!(a.size(), (2, 3));
```

There is no need to create another function that gets the size of a specific dimension like in the Pytorch case.
If you guys agree that this feature is nice to have. Where should the code for such a feature be added? 
I would like to work on it please.

**Comment by coreylowman** [comment]
This is possible via `a.shape()`, which is accessible through the `dfdx::shapes::HasShape` trait.

Want to add an example of this to some of the examples?
