### ISSUE TITLE
Support for TensorRT

### ISSUE THREAD

**Issue by soloist-v** [coreylowman/dfdx#749]
Can we add support for TensorRT to facilitate deployment usage?

**Comment by coreylowman** [comment]
This will likely come through saving a nn to an onnx file (#57), as tensorrt can read onnx. Would that be sufficient?

**Comment by soloist-v** [comment]
Is there a plan to add TensorRT to the cudarc crate? This would eliminate the need to manually write C/C++ code for model deployment.

**Comment by coreylowman** [comment]
It seems like TensorRT only has a c++ api, which would make it hard to wrap using FFI if I'm understanding correctly.

**Comment by soloist-v** [comment]
If that's the case, then it's indeed very difficult to accomplish.

**Comment by soloist-v** [comment]
Can CUDNN_INCLUDE and CUDNN_LIB be added to respectively specify the include and lib directories?
Because I am unable to specify the lib directory on Windows, I need to copy the CUDNN lib files to the project directory in order to compile.

**Comment by coreylowman** [comment]
Is cudarc complaining that its unable to find cudnn? We can probably fix that in the build.rs script of cudarc

**Comment by soloist-v** [comment]
Yes, the error message is "LINK: fatal error LNK1181: cannot open input file 'cudnn.lib'". In fact, if you want to use cl.exe, you also need to execute "cmd /k "D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"" in the command prompt before running "cargo run" in a new terminal, otherwise you may encounter an error saying that cl.exe cannot be found.

**Comment by coreylowman** [comment]
Created a separate issue in cudarc for the linking issues: https://github.com/coreylowman/cudarc/issues/141. Feel free to add more details there.

As far as TensorRT, it does seem like there are some crates that add bindings around it (search tensorrt on crates.io). They look way more complex than normal FFI though. At this point, I'm thinking the support for TensorRT will be provided through export dfdx models to ONNX models, and then using other tensorrt tools to read in the onnx model & execute it. Again, the onnx model export is tracked in the previously mentioned issue (#57).

Going to close this one for now.

**Comment by soloist-v** [comment]
Thank you for your advice, I have already added it.
