### ISSUE TITLE
Make more functions/modules/traits public

### ISSUE THREAD

**Issue by M1ngXU** [coreylowman/dfdx#796]
When creating new models I always find myself needing to use "private" functions/modules/traits, and I thus have my own branch of dfdx that exposes more "internal" stuff, especially:
- `Gradients`: It's impossible to implement a custom Model with its own backpropagation as all methods are `pub(crate)`
- `TensorLike`/`GhostTensor`: `TensorLike` is useful to get a reference to the data without cloning it and `GhostTensor` for `Gradients` (though it's not necessary)
- special cpu/cuda functions: `index_to_i`, `launch_cfg` are also required to compute forward/backward passes
- and probably much more ...

Can the visibility be changed, maybe only with an additional feature?

**Comment by coreylowman** [comment]
Mentioning #814 which also made a variety of apis public

**Comment by coreylowman** [comment]
I'm going to close this for now - if anyone has specific requests, just open a PR with the change, definitely open to whatever people want (I've discovered a lot through trying to make an external nn layer)
