### ISSUE TITLE
Consider adding a `Tape` type where the tape is optional, e.g. `Option<Arc<Mutex<OwnedTape<_, _>>>>`

### ISSUE THREAD

**Issue by emchristiansen** [coreylowman/dfdx#837]
Consider adding a `Tape` type where the tape is optional, e.g. `Option<Arc<Mutex<OwnedTape<_, _>>>>`

At a high level, my forward fn looks like this:

```rust
// I'm using `Tensor` as a drop-in for f32, so I can get gradients.
// Note: I'm also doing ML-style big tensor ops at other points in the code.
type Scalar<T> = Tensor<Rank0, f32, Cpu, T>;

// `forward` maps variable-length vecs of structured inputs to variable-length
// vecs of structured outputs.
fn forward(
  &self,
  input: &[InputStruct<Scalar<T>>],
) -> Vec<OutputStruct<Scalar<T>>> { ... }
```

Here, it's natural for `OutputStruct` (and maybe `InputStruct`) to contain some scalars which are tracked and some which are not.
For example, my forward fn uses both fixed physical models and learned models.
The tensors which are downstream of the learned models should be tracked on the tape, but it really doesn't make any sense to track the outputs of the physical models (I'm not training them).
I _could_ do `let fixed_output = fixed_output.put_tape(Default::default());`, but that's weird because it sets up gradient tracking when it's not needed.

So my proposed solution is to create yet another (🥳🙄) `Tape` type, essentially `Option<Arc<Mutex<OwnedTape<_, _>>>>`.
So, I'd have `type Scalar = Tensor<Rank0, f32, Cpu, OptionTape<f32, Cpu>>`.

Note, this means that you would have to `unwrap` before calling `backward`, but I don't think that's worse than the current workaround where I need to be careful not to call `backward` on an output with a dummy tape.
Actually, it's probably nicer to get a clean crash than the wrong gradient value.

Thoughts?

**Comment by coreylowman** [comment]
Hmm could you just have two input arrays (or a tuple of them) which separates the ones that are tracked (and have tapes) and ones that are not?

I think we could probably just add an `impl<T: Tape> Tape for Option<T>`, which would let you do `Option<OwnedTape>`, `Option<Arc<Mutex<OwnedTape>>>`, etc

**Comment by emchristiansen** [comment]
After playing with this, I don't find it useful - I can do what I want using the other tape variants.
So, I'll close this!
