### ISSUE TITLE
Deriving Shape for C like enums

### ISSUE THREAD

**Issue by ZacharyKamerling** [coreylowman/dfdx#856]
**Problem**
Building a classifier with C like enums is awkward. Const generics doesn't work with const functions so we can't use `std::mem::variant_count` as a type parameter.

**Possible Solution?**
Allow users to derive `Shape` for C like enums.

```
#[derive(Shape)]
enum ABC {
    A, B, C
}
```

**Comment by coreylowman** [comment]
I don't think there should be anything stopping you from `impl dfdx::shapes::Shape` for your custom enum. Let me know if you find a blocker.
