### ISSUE TITLE
Expose AddDim to public API

### ISSUE THREAD

**Issue by LeoDog896** [coreylowman/dfdx#859]
I'm writing an API for my own library that has a generic Device as an input (instead of using `AutoDevice`, that way users can choose what device they want to pass in (or autodevice as default).

My implementation requires using the stacking util (using batches), which requires an extra generic restriction on some Shape: `AddDim<usize>`.

**Comment by coreylowman** [comment]
SHould be a relatively simple change if you want to open a PR for this
