### ISSUE TITLE
Cannot install cargo package 0.8.0

### ISSUE THREAD

**Issue by schlagenhauf** [coreylowman/dfdx#86]
I'm not sure if this is a problem of this package, but i have problems installing dfdx 0.8.0 as a dependency:

```
❯ cargo build
    Updating crates.io index
error: failed to select a version for the requirement `dfdx = "0.8.*"`
candidate versions found which didn't match: 0.7.0, 0.6.0, 0.5.2, ...
location searched: crates.io index
required by package `rust_ml v0.1.0 (/home/pntagrl/tmp/rust_ml)`
❯ cargo search dfdx
dfdx = "0.8.0"           # Ergonomic auto differentiation in Rust, with pytorch like apis.
```

`Cargo.toml`:
```
[package]
name = "rust_ml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfdx = "0.8.*"
```

What am I missing?

**Comment by coreylowman** [comment]
@schlagenhauf  That's odd, I can't reproduce on my windows or ubuntu machines. What kinda machine are you on?

Does it work if you specify exactly "0.8.0"? Does running `cargo update` beforehand change anything?

**Comment by schlagenhauf** [comment]
Ok the solution was to run `rustup update`.

Weird that only this package didn't work for me. Anyway, sorry for the noise.

---

For completeness, I'm on Arch Linux and setting 0.8.0 specifically didn't change anything, `cargo update` and `cargo build` produced the same error.
