### ISSUE TITLE
Different results when CPU feature is on vs off

### ISSUE THREAD

**Issue by jafioti** [coreylowman/dfdx#871]
I get different results for operations like matmul when the CPU feature is turned on vs when it's off. I think the naieve gemm might be incorrectly implemented, but not sure if thats the issue.The differences aren't trivial, so definitely not precision errors.

**Comment by ViliamVadocz** [comment]
Can you provide a small example to reproduce the problem?

**Comment by coreylowman** [comment]
This was discussed in https://github.com/coreylowman/dfdx/issues/560 - this is expected.
