### ISSUE TITLE
Question / clarification regarding heap allocations

### ISSUE THREAD

**Issue by emchristiansen** [coreylowman/dfdx#879]
_Asking here because I didn't see this explicitly covered in the docs._

In what conditions can a user know that a given piece of `dfdx` code won't perform any heap allocations?
E.g., will I be good if i simply ensure all my tensors have static shapes?

I don't have a perfect apples-to-apples comparison, but I have the impression my `dfdx` code is maybe 2x to 4x slower than equivalent code written in JAX and compiled to XLA.
In the XLA version, the full data flow graph including the tensor shapes is statically known, so there's no need for dynamic allocation, and I'm wondering if that might be the source of the apparent difference in speed.

**Comment by coreylowman** [comment]
If you want to add details about this to the docs feel free to open a PR! Probably good at the mod level tensor documentation
