### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by jafioti** [coreylowman/dfdx#88]
I think if this project is to grow and have multiple contributors, it would make sense to have a place to talk and have faster back and forth than github issues. Lots of rust projects use discord servers for communication, so I think that would be a reasonable way to go.

**Comment by jafioti** [comment]
I'd say readme is good enough

**Comment by coreylowman** [comment]
Added badge to readme. Let's keep this issue open for a bit to make it easier for people to find
