### ISSUE TITLE
Batched Matrix Multiply

### ISSUE THREAD

**Issue by jafioti** [coreylowman/dfdx#92]
For transformers, it's necessary to multiply input (Tensor<Batch, Seq, Embed>) by weight (Tensor<Embed, Embed>). One way of achieving this is to flatten the input to Tensor<Batch + Seq, Embed> and then do normal multiplication, but I think there is a better way. Plus, reshaping right now isn't supported yet, and even when it is will require nightly. 

I can implement bmm, but I'm unsure what the best way to go about it is right now. `matrixmultiply` doesn't have a function for it.

**Comment by jafioti** [comment]
Once this is added, we can also add it to the Linear layer, allowing Tensor<B, S, E> to be passed into Linear<E, O>.

**Comment by coreylowman** [comment]
Could potentially be used for conv2d (#1) as well, depending on how the underlying conv implementation works.

for conv batch matmul I was testing out just doing matmul sequentially vs using rayon to parallelize it. I was thinking providing both as an under the hood option, but probably start with the sequential version just for ease of implementation. can do an optimization pass at a later point once it's more fully implemented
