### ISSUE TITLE
oneDNN library

### ISSUE THREAD

**Issue by jczaja** [coreylowman/dfdx#93]
Hi,

I would like to let you know that there exists quite performance wise efficient open source library for CPU (target of optimization is Intel CPU's instruction sets but there is some support for others as well) known as [oneDNN](https://github.com/oneapi-src/oneDNN). This library is quite portable (Linux,Windows) and is using runtime generated assembly code e.g. JIT to implement chosen operations e.g. primitive.  For best performance some architecture changes of your library would be needed, but also you will get benefit if you integrate oneDNN as it is. In detail to get best performance, the data from Your tensor has to be converted(reordered) into memory arrangement(memory layout) recommended by oneDNN operation (primitive). But you could just use your memory arrangement that you already have and get some perf improvement on many operations.

I'm writting this so perhaps you may find it useful and if you decide to take a look I can offer some guidance or answer some questions
as I integrate this library into C++ based deep learning frameworks as part of my day Job (I use Rust by night for my hobby projects).

Thanks very much for your amazing work.

**Comment by coreylowman** [comment]
Thanks for letting me know! Already support linking to intel MKL, so that probably will help this. I think other integrations like GPU may also require storing in a different format.
