### ISSUE TITLE
Derive CanUpdateWithGradients and ResetParams

### ISSUE THREAD

**Issue by jafioti** [coreylowman/dfdx#95]
It seems that `CanUpdateWithGradients` is pretty simple and should be able to be derived so that each tensor in the model is updated with the grads. `ResetParams` is a little more tricky, so we could just have a default random initialization scheme (maybe just uniform 0 to 1), and then if custom initialization is desired, a manual implementation is needed.

Would be great instead of doing this:
```rust
#[derive(Default, Debug, Clone)]
pub struct Linear<const I: usize, const O: usize> {
    pub weight: Tensor2D<O, I, NoneTape>,
    pub bias: Tensor1D<O, NoneTape>,
}

impl<const I: usize, const O: usize> CanUpdateWithGradients for Linear<I, O> {
    fn update<G: GradientProvider>(&mut self, grads: &mut G) {
        self.weight.update(grads);
        self.bias.update(grads);
    }
}
```
we can just do this:
```rust
#[derive(Default, Debug, Clone, CanUpdateGradients)]
pub struct Linear<const I: usize, const O: usize> {
    pub weight: Tensor2D<O, I, NoneTape>,
    pub bias: Tensor1D<O, NoneTape>,
}
```

These changes would of course require a separate proc macros crate though, so it will be a non trivial change.

**Comment by cBournhonesque** [comment]
I'd like to learn more about derive/macros, I'd be happy to work on this

**Comment by cBournhonesque** [comment]
Looking at other procedural macros, it looks like I would have to change a bit the structure of the repo?
Seems like procedural macros have to be in their own crate, so maybe we need to use rust workspaces?

Similar to https://github.com/tokio-rs/tokio 

We would have:
dfdx (git repo)
- dfdx (main crate)
  - Cargo.toml
- dfdx-macros (macros crate)
  - Cargo.toml
- examples (examples crate)
- Cargo.toml

The main Cargo.toml would contain this
```
[workspace]
members = [
  "dfdx",
  "dfdx-macros",
  # Internal
  "examples",
 ]
 
Does that sound good to you?

**Comment by coreylowman** [comment]
I think we can use the [root package](https://doc.rust-lang.org/cargo/reference/workspaces.html#root-package) feature of workspaces to simplify this a bit.

Specifically:
1. Add `[workspace]` at the top of `Cargo.toml`
2. Add a `dfdx-macros/` lib at the *same level* as src
3. Add `dfdx-macros = { path = "./dfdx-macros", optional = true }` under dependencies

I tested this out with a `cargo test --tests --workspace` and both dfdx & dfdx-macros tests ran. Does the same work for you?

**Comment by coreylowman** [comment]
This is now done thanks to rework to TensorCollection
